export const CART_ACTION_TYPES = {
  INCREMENT_ITEM_QUANTITY: "cart/INCREMENT_ITEM_QUANTITY",
  DECREMENT_ITEM_QUANTITY: "cart/DECREMENT_ITEM_QUANTITY",
  DELETE_ITEM_FROM_CART: "cart/DELETE_ITEM_FROM_CART",
};